openapi: 3.0.0
info:
  title: Fit REST API (used by HealthCheck)
  version: 1.0.0
servers:
  - url: https://www.googleapis.com/fitness/v1
paths:
  /users/{userId}/dataSources:
    get:
      summary: Get fit data for a specific time range
      description: Returns metrics such as steps, heart rate, ECG, sleep, blood pressure, pulse, calories, VO₂, and SpO₂ within the specified time range.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: query
          name: startTime
          description: Start time in nanoseconds since epoch.
          required: true
          schema:
            type: integer
        - in: query
          name: endTime
          description: End time in nanoseconds since epoch.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Fitness data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FitnessDataResponse'
        '401':
          description: Unauthorized
        '404':
          description: Data not found

components:
  schemas:
    FitnessDataResponse:
      type: object
      properties:
        steps:
          type: integer
          example: 12000
        heartRate:
          type: number
          format: float
          example: 72.5
        ecg:
          type: string
          example: "Normal sinus rhythm"
        sleep:
          type: string
          example: "7h 30m"
        bloodPressure:
          type: string
          example: "120/80"
        pulse:
          type: integer
          example: 70
        calories:
          type: number
          example: 500.5
        vo2:
          type: number
          example: 42.3
        spo2:
          type: number
          example: 98.0
