openapi: 3.0.0
info:
  title: Google Calendar API (used by HealthCheck)
  version: 1.0.0
paths:
  /calendar/v3/calendars/{calendarId}/events:
    post:
      summary: Insert an event into a calendar
      parameters:
        - in: path
          name: calendarId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event inserted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '409':
          description: Conflict
  /calendar/v3/calendars/{calendarId}/events/{eventId}:
    delete:
      summary: Delete an event
      parameters:
        - in: path
          name: calendarId
          required: true
          schema:
            type: string
        - in: path
          name: eventId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Event deleted
        '404':
          description: Not found
components:
  schemas:
    Event:
      type: object
      properties:
        summary:
          type: string
        description:
          type: string
        start:
          type: object
          properties:
            dateTime:
              type: string
              format: date-time
        end:
          type: object
          properties:
            dateTime:
              type: string
              format: date-time