openapi: 3.0.0
info:
  title: Online Medical Consultations API
  description: API для управления онлайн-консультациями с врачами
  version: 1.0.0
servers:
  - url: https://api.medical-calendar.example.com/v1
    description: Production server

paths:
  /calendars/{calendarId}/events:
    post:
      tags: [Consultations]
      summary: Создать онлайн-консультацию
      operationId: createConsultation
      parameters:
        - $ref: '#/components/parameters/calendarId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultationEvent'
      responses:
        '201':
          description: Консультация создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultationEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /calendars/{calendarId}/events/{eventId}:
    delete:
      tags: [Consultations]
      summary: Отменить консультацию
      operationId: cancelConsultation
      parameters:
        - $ref: '#/components/parameters/calendarId'
        - $ref: '#/components/parameters/eventId'
      responses:
        '204':
          description: Консультация отменена
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    calendarId:
      name: calendarId
      in: path
      required: true
      schema:
        type: string
      description: Идентификатор календаря
    eventId:
      name: eventId
      in: path
      required: true
      schema:
        type: string
      description: Идентификатор консультации
    timeMin:
      name: timeMin
      in: query
      schema:
        type: string
        format: date-time
      description: Минимальное время начала (фильтр)
    timeMax:
      name: timeMax
      in: query
      schema:
        type: string
        format: date-time
      description: Максимальное время начала (фильтр)

  schemas:
    ConsultationEvent:
      type: object
      required: [summary, start, end, conferenceData]
      properties:
        id:
          type: string
          readOnly: true
          description: Уникальный ID консультации
        summary:
          type: string
          description: Тема консультации
          example: "Консультация с кардиологом"
        description:
          type: string
          description: Детали консультации
          example: "Обсуждение результатов ЭКГ"
        start:
          $ref: '#/components/schemas/DateTime'
        end:
          $ref: '#/components/schemas/DateTime'
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/Attendee'
        conferenceData:
          $ref: '#/components/schemas/ConferenceData'
        reminders:
          $ref: '#/components/schemas/Reminders'

    DateTime:
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
          description: Время в формате RFC3339
        timeZone:
          type: string
          description: Часовой пояс
          example: "Europe/Moscow"

    Attendee:
      type: object
      properties:
        email:
          type: string
          format: email
        displayName:
          type: string
        optional:
          type: boolean
          default: false

    ConferenceData:
      type: object
      required: [createRequest]
      properties:
        createRequest:
          type: object
          properties:
            requestId:
              type: string
              description: Уникальный ID для идемпотентности
            conferenceSolutionKey:
              type: object
              properties:
                type:
                  type: string
                  enum: [videoCall]
            status:
              type: object
              properties:
                statusCode:
                  type: string
                  enum: [pending, success, failure]
    Reminders:
      type: object
      properties:
        useDefault:
          type: boolean
        overrides:
          type: array
          items:
            type: object
            properties:
              method:
                type: string
                enum: [email, popup]
              minutes:
                type: integer

  responses:
    BadRequest:
      description: Неверный запрос
    Unauthorized:
      description: Требуется авторизация
    NotFound:
      description: Консультация не найдена

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.medical.example.com/oauth/authorize
          tokenUrl: https://auth.medical.example.com/oauth/token
          scopes:
            consultations:write: Создание и изменение консультаций
            consultations:read: Просмотр консультаций

security:
  - OAuth2:
      - consultations:write
      - consultations:read
